#!/bin/bash
# Adds specified information into a time-formatted diary entry

source settings
source template
if [ ! -d "$main_folder" ] ; then
    mkdir "$main_folder"
fi

new_entry="$(date +%Y%m%d)"
today="$(find "$main_folder" -name "$new_entry")"

usage() {
    echo "Usage: $(basename "$0") -a {data} to add to current day
       $(basename "$0") -d {line} to delete line
       $(basename "$0") -rm to delete file
       $(basename "$0") -p {date} to print entry (default is the current day)
                  'n', 'num', or 'number' afterwards prints line numbers
       $(basename "$0") -e to edit entire current day entry file
                  start with line number to edit only the specified line
                  e.g. '1 hlelo hello'
       $(basename "$0") -s to search through all entries"
    exit 0
}

make_new_entry() {
    touch "$new_entry"
    echo "${template_file//_/\ }" > "$new_entry"
    echo "------------------------------" >> "$new_entry"

    # If no current directory "Year"
    if [ ! -d "$main_folder"/"$(date +%Y)" ] ;
    then
        mkdir "$main_folder"/"$(date +%Y)"
    fi

    # If no current directory "Year/Month"
    if [ ! -d "$main_folder"/"$(date +%Y)"/"$(date +%m)" ] ;
    then
        mkdir "$main_folder"/"$(date +%Y)"/"$(date +%m)"
    fi

    # Move new entry to directory "Year/Month"
    mv "$new_entry" "$main_folder"/"$(date +%Y)"/"$(date +%m)"
    today="$(find "$main_folder" -name "$new_entry")"
}

case $1 in 
    -a | -add )
        shift;
        # Expand @shortcuts if present in settings
        if [ "${1:0:1}" == "@" ] ; then
            set -- "${shortcuts["${1:1}"]}"
        fi
        # current day file does not exist
        if [ ! -f "$today" ] ;
        then
            make_new_entry
        fi
        # current entry file exists and there are words after -a
        if [ "$#" -gt 0 ] ; then
            echo "$(date +%T)" "$@" >> "$today"
        fi
        exit 0
        ;;
    -d | -delete )
        sed -i "$2"'d' "$today"
        exit 0
        ;;
    -rm | -remove )
        rm "$today"
        exit 0
        ;;
    -p | -print )
        shift;
        output="cat"

        if [[ "$1" =~ [n|num|number] ]]; then
            output="cat -n"
            shift;
        fi
        # Expand @shortcuts if present in settings
        if [ "${1:0:1}" == "@" ] ; then
            day="${shortcuts["${1:1}"]}"
            today="$(find "$main_folder" -name "$day")"
        # If not a shortcut, but also not an empty variable (i.e. a date is given)
        elif [ -n "$1" ] ; then
            today="$1"
        fi
        # If the file does not exist
        if [ ! -f "$today" ]; then
            echo "File \"$today$day\" not found"
            exit 1
        fi
        $output "$today"
        exit 0
        ;;
    -e | -edit ) 
        if [ "$#" -gt 4 ] ; then
            echo "Incorrect usage." >&2
            exit 1
        fi
        if [ "$#" -eq 4 ] ; then
            if [[ ! "$3" =~ $(sed -n "$2"'{p;q}' "$today" | "$@") ]]; then
                echo "Word not found in line." >&2
                exit 1
            fi
            sed -i "$2"s/"$3"/"$4"/ "$today"
            sed -i "$2"s/$/" (edited at $(date +%T))"/ "$today"
            exit 0
        fi
        if [[ ! "$2" =~ $("$@" < "$today") ]]; then
            echo "Word not found in file." >&2
            exit 1
        fi
        sed -i s/"$2"/"$3"/ "$today"
        echo "(edited file at $(date +%T))" >> "$today"
        exit 0
        ;;
    -s | -search )
        shift;
        search="grep -r"
        with_count="-c"
        if [[ "$1" =~ [c|count] ]]; then 
            search="${search} ${with_count}"
            shift;
        fi
        $search "$@" "$main_folder"
        exit 0
        ;;
    * )
        usage
        ;;
esac
