#!/bin/bash
# Adds specified information into a time-formatted diary entry

source settings
mkdir "$mainFolder"

newEntry="$(date +%Y%m%d)"
today="$(find "$mainFolder" -name "$newEntry")"

usage() {
    echo "Usage: $(basename "$0") -a {data} to add to current day
       $(basename "$0") -d {line} to delete line
       $(basename "$0") -rm to delete file
       $(basename "$0") -p {date} to print entry (default is the current day)
                  'n', 'num', or 'number' afterwards prints line numbers
       $(basename "$0") -e to edit entire current day entry file
                  start with line number to edit only the specified line
                  e.g. '1 hlelo hello'"
    exit 0
}

makeNewEntry() {
    touch "$newEntry"
    date +%A,_%dth_%B_%Y | sed s/_/\ /g > "$newEntry"
    echo "------------------------------" >> "$newEntry"

    # If no current directory "Year"
    if [ ! -d "$mainFolder"/"$(date +%Y)" ] ;
    then
        mkdir "$mainFolder"/"$(date +%Y)"
    fi

    # If no current directory "Year/Month"
    if [ ! -d "$mainFolder"/"$(date +%Y)"/"$(date +%m)" ] ;
    then
        mkdir "$mainFolder"/"$(date +%Y)"/"$(date +%m)"
    fi

    # Move new entry to directory "Year/Month"
    mv "$newEntry" "$mainFolder"/"$(date +%Y)"/"$(date +%m)"
}

# Expand @shortcuts if present in settings
expandShortcuts() {
    exit 0
}

case $1 in 
    -a | -add )
        shift;
        # current file does not exist, and there are no words to be added
        if [ ! -f "$today" ] && [ ! "$#" -gt 0 ] ; then
            makeNewEntry
            exit 0
        fi
        # current day file does not exist
        if [ ! -f "$today" ] ;
        then
            makeNewEntry
        fi
        # current entry file exists and there are words after -a
        if [ "$#" -gt 0 ] ; then
            echo "$(date +%T)" "$@" >> "$today"
            exit 0
        fi
        ;;
    -d | -delete )
        sed -i "$2"'d' "$today"
        exit 0
        ;;
    -rm | -remove )
        rm "$today"
        exit 0
        ;;
    -p | -print )
        if [ -f "$(find "$mainFolder" -name "$3")" ]; then
            today="$(find "$mainFolder" -name "$3")"
        fi
        if [ "$2" = "number" ] || [ "$2" = "num" ] || [ "$2" = "n" ]; then
            cat -n "$today"
            exit 0
        fi
        cat "$today"
        exit 0
        ;;
    -e | -edit ) 
        if [ "$#" -gt 4 ] ; then
            echo "Incorrect usage." >&2
            exit 1
        fi
        if [ "$#" -eq 4 ] ; then
            if [[ ! "$3" =~ $(sed -n "$2"'{p;q}' "$today" | "$@") ]]; then
                echo "Word not found in line." >&2
                exit 1
            fi
            sed -i "$2"s/"$3"/"$4"/ "$today"
            sed -i "$2"s/$/" (edited at $(date +%T))"/ "$today"
            exit 0
        fi
        if [[ ! "$2" =~ $("$@" < "$today") ]]; then
            echo "Word not found in file." >&2
            exit 1
        fi
        sed -i s/"$2"/"$3"/ "$today"
        echo "(edited file at $(date +%T))" >> "$today"
        exit 0
        ;;
    -s | -setup )
        shift;
        if [ $# -gt 1 ]; then
            echo "Set one folder to store entries." >&2
            exit 1
        fi
        if [ ! -d "$1" ]; then
            echo "Directory does not exist." >&2
            exit 1
        fi
        # Set main folder
        sed -i 3s/.*/export\ mainFolder="$1"/ ./setFolder
        exit 0
        ;;
    * )
        usage
        ;;
esac
